---
- name: "add stackdriver's gpg key"
  apt_key: 
    url: "{{ stackdriver_package_repo_gpg }}"
    state: present
  tags:
    - stackdriver

- name: "add the stackdriver apt repository."
  apt_repository:
    repo: "deb {{ stackdriver_package_repo }} {{stackdriver_package_repo_codename_prefix}}{{ ansible_lsb.codename }}{{stackdriver_package_repo_codename_suffix}} main"
    state: present
  tags:
    - stackdriver

- name: "install the stackdriver agent."
  apt:
    name: "{{ stackdriver_collectd_package }}"
    state: present 
    update_cache: yes
  tags:
    - stackdriver
