---
- name: "add stackdriver's gpg key"
  apt_key: 
    url: "https://app.stackdriver.com/RPM-GPG-KEY-stackdriver" 
    state: present
  tags:
    - stackdriver

- name: "add the stackdriver apt repository."
  apt_repository:
    repo: "deb {{ stackdriver_package_repo }} {{ ansible_lsb.codename }} main"
    state: present
  tags:
    - stackdriver

- name: "install the stackdriver agent."
  apt:
    name: "{{ stackdriver_collectd_package }}"
    state: present 
    update_cache: yes
  tags:
    - stackdriver
